matrix:
  - name: blog posts
    pipeline:
      - pyspelling.filters.markdown
      - pyspelling.filters.html:
          ignores:
            - code
            - pre
    sources:
      - _posts/**/*.md
      - _drafts/**/*.md
    dictionary:
      wordlists:
        - .wordlist.txt
      output: .wordlist.dic
