title: Martyn's musings
description: Random thoughts in no particular order
url: https://mhemeryck.github.io
author: Martijn Hemeryck
email: martijn.hemeryck@gmail.com

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark"
  back_home_text: ".."
  date_format: "%Y-%m-%d"

plugins:
  - jekyll-remote-theme

favicon: logo.png
permalink: /:year-:month-:day/:title

exclude:
  - docker-compose.yml
  - tags
