remote_theme: daattali/beautiful-jekyll@5.0.0

title: Martyn's musings
url: "https://mhemeryck.github.io"
url-pretty: blog.mhemeryck.com
author: Martijn Hemeryck

navbar-links:
  About Me: "https://cv.mhemeryck.com"

social-network-links:
  email: "martijn.hemeryck@gmail.com"
  github: mhemeryck
  twitter: MartijnHemeryck
  linkedin: martijn-hemeryck-67896245

share-links-active:
  twitter: true
  linkedin: true
  facebook: true

future: true

timezone: "Europe/Brussels"
highlighter: rouge
permalink: /:year-:month-:day/:title

gtag: G-2YN0MRTT7R

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - docker-compose.yml
