name: CI

on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install prettier
        run: |
          sudo npm install --global prettier

      - name: Check markdown formatting
        run: |
          prettier -c **/*.md
